### PR TITLE
docbuild update

### PR DESCRIPTION
**Pull request by heckj**
This should render the docs correctly with `export TOOLCHAIN=swift` - I verified it locally with the latest swift 5.6 toolchain installed.

There's something slightly awry with the package plugin and the nightly toolchain, so I shifted away from it - that being the weak point. At one point I got an error in the dynamic package tooling compilation stage about the plugin not conforming to the package manager's command plugin protocol, but I'm not getting that result consistently, which is really weird.

In any case, this doesn't use the new package manager plugin mechanisms, but otherwise works cleanly - so it should smooth the path to generating docs.

### CODE REVIEW

**Comment by nicklockwood** [comment]
Amazing, thanks!

**Comment by nicklockwood** [comment]
@heckj Should I add all_identifiers.txt and all_symbols.txt to .gitignore? They are recreated each time I run the build script.

**Comment by heckj** [comment]
Yeah, I do - we can even just pull that from the script. I used it to get a dumped list of all the symbols to make it easier to organize things and see what was there.

**Comment by nicklockwood** [comment]
@heckj the generated docs folder has a blank index.html file, and then the actual docs are located at the subpath /documentation/euclid, which is a bit awkward for the github site since it means I have to link directly to the subpath anyone who comes to the site directly won't be able to find the docs. Is there any way to fix that?

**Comment by heckj** [comment]
I suspect there is, but honestly not that I've yet found. And yeah, it's darned awkward!

There's experimental mention of a optional header HTML file, but I haven't sorted if that's a path to what we'd like (header for the set, vs. header for something else) - so right now I'm just linking directly to that "lower" directory structure from the top level of repo, annoying as that is.

**Comment by nicklockwood** [comment]
@heckj thanks! One more thing - the md files in the Euclid.docc/Extensions directory look like they were generated automatically, but I'm not clear how. Is there another script or something for updating those?

**Comment by heckj** [comment]
Nope, I'm sorry. Those were hand authored by yours truly. Although that is what I used the list of symbols that the docbuild.bash script generated. My general process was:
- generate a list of all the symbols and sort them
- select the set pertaining to a specific class, struct, etc - and copy them into an Extension file
- group them with ### headings into sets based on what you'd do with them, mimicking a lot of Apple's structural setup there (they're always prefixed with gerunds, such as "Creating", "Inspecting", and so on)

In practice, as you update the API, you'll see new methods appearing beneath the organized sets if they're not in that list of symbols, so it's pretty quickly to identify them and shift them up to where they're relevant, move deprecated methods (if any) to the bottom of each organization section, or create new sections and re-order things if that all changes.

**Comment by nicklockwood** [comment]
@heckj something I've noticed is that rebuilding the docs is very noisy in terms of diffs because the order of the JSON file contents seems to be randomized. Is there anything we can do about that? It would be great to be able to see what's actually changed in the git history.

**Pull request merged**
