### PR TITLE
Feature/vertex color component

### PR DESCRIPTION
**Pull request by zilmarinen**
Adds a .color property to the Vertex to allow for per vertex colors when creating SCNGeometry.

Continuation from this [PR](https://github.com/nicklockwood/Euclid/pull/61) which I mistakenly closed when trying to rebase on develop.

### CODE REVIEW

**Comment by zilmarinen** [comment]
@nicklockwood this has now all been rebased on develop. I like the vector semantic changes by the way 👍

You [mentioned here](https://github.com/nicklockwood/Euclid/pull/61#issuecomment-967002936) that this PR is on hold due to a serialisation issue. Is this the same issue [I raised on the previous PR](https://github.com/nicklockwood/Euclid/pull/61#issuecomment-966433088), or is this another separate issue?

**Comment by nicklockwood** [comment]
@zilmarinen 

> Is this the same issue I raised on the previous PR

Yes, it's the issue you raised.

**Comment by zilmarinen** [comment]
Great, thanks for clarifying.

I shall spend some time investigating a resolution.

**Comment by zilmarinen** [comment]
@nicklockwood it looks like this may be an issue with the way the polygons are encoded around [this check to see if vertex information can be omitted](https://github.com/nicklockwood/Euclid/blob/d6f826285cd8174af2f6c5429ff1240954c35b4e/Sources/Polygon.swift#L89).

From inspecting the [exported meshes](https://gist.github.com/zilmarinen/1c5d9d7a4e1af11aea3559cac517ad7f), it appears that only the positions for each polygon are being serialised so the color component is lost which then defaults to clear.

Would simply changing this to include a check for colors suffice?

`vertices.allSatisfy({ $0.texcoord == .origin && $0.normal == plane.normal && $0.color == .clear })`

**Comment by zilmarinen** [comment]
I have confirmed that this is a symptom when not specifying UVs for vertices. I have added UVs for each face polygon and everything appears to be rendering correctly when exporting.

**Comment by nicklockwood** [comment]
@zilmarinen sorry for the long delay, but I finally had a chance to look into this properly. I've merged a solution into develop - please take a look and check you're happy with it. Things to note:

1) A problem with the previous solutions was that they caused the Example project to render a blank object. After some investigation I realized that this was because the vertex color is multiplied by the mesh material, so using a clear color to mean "ignore the color" make the object transparent. Changing the default vertex color to white instead solves the problem (I think we may have discussed this before, but I'm not sure when/where). 
2) The custom Metal renderer you wrote before doesn't seem to be needed - SceneKit is quite happy to render vertex colors out of the box.

There isn't currently a way to get Euclid to generate vertex colors for standard shapes, but you can either build a mesh with vertex colors polygon-by-polygon, or change the default color in `Vertex.init(unchecked:)` to something other than white, which will show up in the Example project, e.g.

```swift
self.color = color ?? .white.withAlpha(0.5) // makes mesh 50% transparent
```

or 

```swift
self.color = color ?? .gray // makes mesh darker
```

**Comment by nicklockwood** [comment]
I've added a color property to PathPoint, so it's now possible to create vertex-colored geometry fairly easily, for example:

```swift
let mesh = Mesh.lathe(Path.curve([
    .point(0, -1, color: .red),
    .curve(-1, 0, color: .green),
    .point(0, 1, color: .blue),
]))
```
Screenshot 2021-12-31 at 14 19 59

**Comment by nicklockwood** [comment]
Landed in 0.5.16

**Comment by zilmarinen** [comment]
@nicklockwood Apologies for the delayed response. This is perfect, thank you very much!

**Pull request closed without merging**
