### PR TITLE
Documentation (DocC) trial PR

### PR DESCRIPTION
**Pull request by heckj**
I wasn't sure if this project would be interested in leveraging DocC, so I thought I'd stub out the basics and open this trial/draft PR to see what you think.

The documentation catalog is added so that you can build the docs from either the Xcode project or from the Package.swift file directly. Supporting the Package.swift capability means required updating the swift-tools comment to version 5.5 (from 5.1). I'm not sure if that's acceptable or not.

WIthout that line, the documentation can still be built (and exported) from Xcode through the Xcode project.

DocC doesn't _yet_ have the ability to drop out a bunch of static HTML files that can be hosted - say in Github Pages - but that's being actively worked on, and I'd be happy to help set that up if you're so inclined. 

My original goal was to start to take some of what's in the README that talks about the various types and to embed that as documentation comments into the sources itself.

If this would be better targeted at the 'develop' branch, I'm happy to close this PR and create a new one.

To see this in action, it's probably easiest to check out this branch ([`heckj/docc-trial`](https://github.com/heckj/Euclid/tree/docc-trial)), open either Package.swift or the Xcode project with Xcode (13.0+), and run Product > Build Documentation.

### CODE REVIEW

**Comment by nicklockwood** [comment]
@heckj hi, sorry for not responding earlier. This looks really cool!

I'm not 100% sure I want to upgrade the project to Swift 5.5 yet as ShapeScript still supports Mojave, and it's convenient to be able to build on a Euclid on a Mojave device for debugging/testing. Perhaps I can somehow maintain a branch with DocC support, and export the docs from there as HTML or markdown?

**Comment by heckj** [comment]
No worries, this was primarily exploratory to see if you think it'd benefit the library. I suspected that shifting up to require Swift 5.5 might be off the table since I know you support older platform versions. Figured that might be a bit of a deal breaker. ;-)

If you don't mind making a swift5.5 branch or such, I'd be happy to apply the doc-writing to that that branch (re-targeting this PR, or closing it and making a new one with the relevant changes).

**Comment by nicklockwood** [comment]
@heckj that sounds fantastic! I've created a suitable branch here: https://github.com/nicklockwood/Euclid/tree/feature/documentation

**Comment by heckj** [comment]
replaced with (Work in progress) PR #77

**Pull request closed without merging**
