### PR TITLE
Vector semantics: line segment position (2/7)

### PR DESCRIPTION
**Pull request by jkalias**
Overview of remaining refactoring steps from #37:

`line.origin` -> `Position` _[done]_
`lineSegment.start/end` -> `Position` **[this PR]**
`pathPoint.position` -> `Position` _[pending]_
`transform.offset` -> `Distance` _[pending]_
`transform.scale` -> `Distance` _[pending]_
`vertex.position` -> `Position` _[pending]_
`Plane(normal: Direction, pointOnPlane: Vector)` -> `pointOnPlane` should be `Position` _[pending]_

### CODE REVIEW

**Comment by jkalias** [comment]
Hi @nicklockwood, can you please help me understand something?

They way I am developing these new/updated features is by branching from my develop branch (which tracks your upstream develop branch). I occasionally have to merge your develop into mine and afterwards in the feature branch, so it can be merged without conflicts.

Q1: Why do I see conflicts in this case here?
Q2: Why do I see previous commits which are not related to the feature being developed, and which have already been merged in your develop branch?

I'd be grateful if you could shed some light into this.

**Comment by nicklockwood** [comment]
> Q1: Why do I see conflicts in this case here?
> Q2: Why do I see previous commits which are not related to the feature being developed, and which have already been merged in your develop branch?

I'm constantly releasing minor updates from the develop branch, and although I've merged your PRs, they're still under development and aren't ready to be included in a release yet, so for now I'm having to rebase them on top of the changes I'm making, which changes the develop branch history.

Normally this wouldn't be an issue because once merged, a PR becomes my responsibility and I can fix any conflicts. But because you're actively developing further updates you're running into conflicts frequently.

You can just ignore the conflicts and I'll resolve them when I merge your PRs.

**Comment by jkalias** [comment]
Does this mean that my workflow is wrong? I thought I should be developing on the `develop` branch, and trying to merge my changes in _your_ `develop` branch, I hope this is the correct way to move on.

**Comment by nicklockwood** [comment]
You should branch from my develop branch, but you should just take a snapshot of it whenever you start work and not merge updates from the develop branch back into your branch periodically. Doing that creates conflicts which make it harder for me to merge your changes later since your branch history now includes copies of my commits as well as your own.

**Comment by jkalias** [comment]
Aha ok, thanks for the clarification. By regularly merging your develop into mine I thought I was helping out, my apologies for the inconvenience. I'll stick to your advice then.

**Comment by nicklockwood** [comment]
>  By regularly merging your develop into mine I thought I was helping out, my apologies for the inconvenience

No problem! FWIW the correct way to do this would be to use `git rebase origin/develop` instead of `git merge origin/develop`.

Rebase merges the changes in your branch on top of the latest develop changes instead of merging develop changes into your branch (which creates the correct history, without spurious merge commits). The conflicts from rebase can be a bit more difficult to resolve though, so I'm happy to do this myself.

**Comment by jkalias** [comment]
One last question: should I rebase on my own (forked) develop (`git rebase origin/develop`) or your own one (`git rebase upstream/develop`)?

**Comment by nicklockwood** [comment]
There's no need to ever rebase on your own develop unless you've changed it.

**Comment by jkalias** [comment]
I tried to keep my develop in sync with yours, but apparently this is not needed.
Thanks for taking the time to reply, I appreciate it

**Comment by jkalias** [comment]
@nicklockwood can it be that something didn't work as supposed in this PR?
`LineSegment` on the `develop` branch is still using `Vector`, am I missing something?

**Comment by nicklockwood** [comment]
@jkalias sorry about that - the LineSegment changes must have gotten lost in a rebase. Do you still have them locally? Otherwise I can recreate the commit.

**Comment by jkalias** [comment]
Unfortunately I don't have them, and I also completely deleted my branch.

**Comment by nicklockwood** [comment]
@jkalias I believe I've recreated the LineSegment changes - can you check latest develop and let me know?

**Comment by jkalias** [comment]
@nicklockwood yea, it's in, now line segment has `start` and `end` as `position`

**Pull request merged**
