### PR TITLE
Vector semantics: path point (3/7)

### PR DESCRIPTION
**Pull request by jkalias**
Overview of remaining refactoring steps from #37:

`line.origin` -> `Position` _[done]_
`lineSegment.start/end` -> `Position` _[done]_
`pathPoint.position` -> `Position` **[this PR]**
`transform.offset` -> `Distance` _[pending]_
`transform.scale` -> `Distance` _[pending]_
`vertex.position` -> `Position` _[pending]_
`Plane(normal: Direction, pointOnPlane: Vector)` -> `pointOnPlane` should be `Position` _[pending]_

### CODE REVIEW

**Comment by jkalias** [comment]
@nicklockwood I think we need to find a better strategy here. I started working 2 hours ago on this, fetching a fresh copy of your `develop` branch. Once I applied all the missing changes from my previous PRs, I started with `pathPoint.position`, and once I finished, I rebased my branch, as we discussed last time.

Now I get all sorts of merge issues, and many of changes are again lost (this is why I haven't resolved the conflicts before creating the PR).

I think it doesn't make a lot of sense if we both work on the same files and lines simultaneously. Please advise how you think we can move on more efficiently.

**Comment by nicklockwood** [comment]
@jkalias I think this is unavoidable. Even if you worked on a side branch instead of develop, you'd either have to resolve conflicts each time you want to open a PR, or leave all merging until the very end of this process, at which point Euclid would probably be unrecognizable from the branch you started from.

I'm happy for you to skip the rebase step for each PR and let me handle it. The lost commits last time were due to the confusing merge history, which shouldn't happen in future.

If this PR is good to go, I'll merge it, then you can use the current state of develop once that's landed as the starting point for your next PR?

**Comment by jkalias** [comment]
@nicklockwood ok, let’s do it that way then. I’ll always start from a fresh develop copy, implement my changes and then let you handle the merge conflicts.

**Comment by nicklockwood** [comment]
@jkalias merged.

**Pull request merged**
